# Generated by Django 3.2.8 on 2022-02-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('played_hole', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playedhole',
            name='driver_distance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
